### ISSUE TITLE
[Dialog][v2] open Function with `directory: true` Fails to Return Path

### ISSUE THREAD

**Issue by Blist** [tauri-apps/plugins-workspace#1060]
When using the open function from the JavaScript API with the directory option enabled, the function fails to return a path, contrary to the expected behavior where a path or FileResponse object should be returned. Disabling the directory option allows the function to return a FileResponse as expected.

**Steps to Reproduce:**
Implement the open function with the following options:
```typescript
const selected = await open({
    directory: true,
    multiple: false,
    recursive: true
});
console.log(selected);
```
Observe that no path is returned in the console output when the directory option is set to true.
Modify the open function options by setting directory to false or omitting it.
Observe that a FileResponse object is correctly returned and logged in the console.

**Expected Behavior:**
When directory is set to true, the open function should return a path or object indicating the selected directory.

**Actual Behavior:**
The open function returns undefined or no output when directory is set to true.

```bash
❯ bun tauri info
$ tauri info

[✔] Environment
    - OS: Manjaro 23.1.3 X64
    ✔ webkit2gtk-4.1: 2.42.5
    ✔ rsvg2: 2.57.1
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 21.6.2
    - npm: 10.5.0
    - bun: 1.0.29

[-] Packages
    - tauri [RUST]: 2.0.0-beta.10
    - tauri-build [RUST]: 2.0.0-beta.8
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.4
    - @tauri-apps/cli [NPM]: 2.0.0-beta.8

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; media-src 'self' asset: https://asset.localhost
    - frontendDist: ../public
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

**Comment by amrbashir** [comment]
this works fine on Windows, might be an issue on Linux only, cc @FabianLars

**Comment by FabianLars** [comment]
Works for me on Linux too, but only tested Ubuntu (gnome) for now.

@Blist It shouldn't matter since we're using gtk but which DE are you using? And can you make sure the npm and rust packages for the plugin are on their latest v2 beta versions?

**Comment by Blist** [comment]
Hello,

I have two computer, One on archlinux i3 (Xorg) with nvidia and the other on Archlinux sway (wayland) with radeon. I encounter the same problem on the both.

bellow my package.json
```json
{
  "name": "supersamplons",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "check": "svelte-check --tsconfig ./tsconfig.json",
    "tauri": "tauri"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.5.1",
    "@fortawesome/free-solid-svg-icons": "^6.5.1",
    "@fortawesome/pro-duotone-svg-icons": "^6.5.1",
    "@fortawesome/pro-light-svg-icons": "^6.5.1",
    "@fortawesome/pro-regular-svg-icons": "^6.5.1",
    "@fortawesome/pro-solid-svg-icons": "^6.5.1",
    "@fortawesome/pro-thin-svg-icons": "^6.5.1",
    "@tauri-apps/api": "^2.0.0-beta",
    "@tauri-apps/plugin-dialog": "^2.0.0-beta.2",
    "@tauri-apps/plugin-fs": "^2.0.0-beta",
    "@tauri-apps/plugin-process": "^2.0.0-beta.2",
    "@tauri-apps/plugin-sql": "^2.0.0-beta",
    "svelte-fa": "^4.0.2"
  },
  "devDependencies": {
    "@sveltejs/vite-plugin-svelte": "3.0.1",
    "@tailwindcss/typography": "^0.5.10",
    "@tauri-apps/cli": "^2.0.0-beta",
    "@tsconfig/svelte": "^5.0.0",
    "@types/eslint": "^8.44.8",
    "@typescript-eslint/eslint-plugin": "^6.13.2",
    "@typescript-eslint/parser": "^6.13.2",
    "autoprefixer": "^10.4.18",
    "daisyui": "latest",
    "eslint": "^8.55.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-plugin-import": "^2.29.0",
    "eslint-plugin-prettier": "^5.0.1",
    "eslint-plugin-svelte": "^2.35.1",
    "postcss": "^8.4.35",
    "prettier": "^3.1.0",
    "sass": "^1.69.5",
    "svelte": "^5.0.0-next.37",
    "svelte-check": "^3.6.2",
    "svelte-preprocess": "^5.1.1",
    "tailwindcss": "^3.4.1",
    "tslib": "^2.6.0",
    "typescript": "^5.0.2",
    "vite": "5.0.2"
  }
  ```
  
  And my cargo.toml
  ```toml
  [package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = ["protocol-asset"] }
tauri-plugin-dialog = "2.0.0-beta.2"
tauri-plugin-fs = "2.0.0-beta" 
tauri-plugin-persisted-scope = "2.0.0-beta"  
tauri-plugin-sql = {features = ["sqlite"], version = "2.0.0-beta" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri-plugin-process = "2.0.0-beta.2"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
```
