### ISSUE TITLE
[store][v2] Deleted the store file, but after exiting, the file was restored.

### ISSUE THREAD

**Issue by ddki** [tauri-apps/plugins-workspace#1102]
Operating System: Windows 10 19045.4170
Edge Version: 122.0.2365.92

I am using the `store` to store multiple files, and the `store.save()` method is used to save the files. During the program runtime, some operations using `tauri-plugin-fs` are used to delete some files. It work good. However, after exiting the program, these files are restored, which is not the desired outcome.                   -translate by AI.

The store file directory structure is as follows:
```sh
│  .window-state
│  active-config.json
│  settings.json
│
└─config
        1138de9f-f6b7-4f7e-9b5d-6a9194526802.json
        7adaab45-eb35-4fb9-a4fe-82080cb1db01.json
        df7dfab6-dd14-41ee-9487-44b7514c8dca.json

```

package.json
```json
		...
        "@tauri-apps/api": "2.0.0-beta.6",
		"@tauri-apps/plugin-fs": "2.0.0-beta.2",
		"@tauri-apps/plugin-process": "2.0.0-beta.2",
		"@tauri-apps/plugin-store": "2.0.0-beta.2",
		...
```

Cargo.toml
```toml
[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = ["devtools", "config-json5"] }
tauri-plugin-shell = "2.0.0-beta"
tauri-plugin-dialog = "2.0.0-beta"
tauri-plugin-updater = "2.0.0-beta"
tauri-plugin-single-instance = "2.0.0-beta"
tauri-plugin-store = "2.0.0-beta"
tauri-plugin-window-state = "2.0.0-beta"
tauri-plugin-log = "2.0.0-beta"
tauri-plugin-fs = "2.0.0-beta"
```

capabilities:
```json
		....
		"fs:default",
		"fs:write-all",
		"fs:allow-remove",
		"fs:allow-appdata-meta",
		"fs:allow-appdata-meta-recursive",
		"fs:allow-appdata-read",
		"fs:allow-appdata-read-recursive",
		"fs:allow-appdata-write",
		"fs:allow-appdata-write-recursive",
		"fs:allow-app-meta",
		"store:allow-get",
		"store:allow-set",
		"store:allow-save",
		"store:allow-has",
		"store:allow-load",
		"store:allow-clear",
		"store:allow-delete",
		"store:allow-values",
		"window-state:allow-save-window-state",
		"window-state:allow-restore-window-state"
		....
```
