### ISSUE TITLE
Updater ISSUE in Windows Installer .msi

### ISSUE THREAD

**Issue by Runkang10** [tauri-apps/plugins-workspace#1449]
The updater on Windows instead of running the installation, the Windows Installer window appears with the **arguments**.

Image (Displayed in italian):
![image](https://github.com/tauri-apps/plugins-workspace/assets/164545653/5c5926d5-4d81-420f-9694-7511b7540fdc)

**Comment by amrbashir** [comment]
Can you please provide more info about your tauri version and the updater plugin version?

**Comment by Runkang10** [comment]
[-] Packages
    - tauri [RUST]: 2.0.0-beta.22
    - tauri-build [RUST]: 2.0.0-beta.17
    - wry [RUST]: 0.40.1
    - tao [RUST]: 0.28.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.13
    - @tauri-apps/cli [NPM]: 2.0.0-beta.20

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite

I'm using the latest version in beta of Tauri (Updater, Shell ...)

**Comment by Runkang10** [comment]
The same ISSUE also appears in executable installer and shows `msiexec.exe` with instruction of parameters and arguments.

**Comment by songjiachao** [comment]
same problem when I  update to 2.0.0-beta.7
<img width="1273" alt="image" src="https://github.com/tauri-apps/plugins-workspace/assets/70792885/14f7f474-56fd-4481-9017-6ac2544975b3">

**Comment by songjiachao** [comment]
![image](https://github.com/tauri-apps/plugins-workspace/assets/70792885/3244445d-e9d5-4bc3-b29b-ebaf311f7db7)

**Comment by Runkang10** [comment]
YES, this is the problem using the latest version of Tauri Updater plugin. The problem is the lack of running the installer with the argument: /quite, /passive ... as it was in version 1v of Tauri now removed in the configurations.

**Comment by pymete** [comment]
Same problem.
https://discord.com/channels/616186924390023171/731495028677148753/1250023043649110089

![image](https://github.com/tauri-apps/plugins-workspace/assets/133960549/b9ff04b6-9607-429c-bc74-ebfdcab974dc)

`@tauri-apps/plugin-updater` npm package version: 2.0.0-beta.5
<img width="354" alt="image" src="https://github.com/tauri-apps/plugins-workspace/assets/133960549/2131c551-a16e-469c-8baa-cd3cfc34d6f7">

`tauri-plugin-updater` rust package version: 2.0.0-beta.7
<img width="517" alt="image" src="https://github.com/tauri-apps/plugins-workspace/assets/133960549/6a1a76a6-deb8-4f00-a9be-911f88679cd2">

I can give any other information needed.

**Comment by Runkang10** [comment]
Wait in the updater plugin configuration, is the `windows` configuration still there or not?

In the repository documentation there are only `endpoints` and `pubkey`.

I found something here: [https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/updater/tests/app-updater/tauri.conf.json](https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/updater/tests/app-updater/tauri.conf.json)

![image](https://github.com/tauri-apps/plugins-workspace/assets/164545653/6f1119f5-e706-44bf-92e0-07ed536d1214)

**Comment by pymete** [comment]
Yeah, it's right there.
<img width="315" alt="image" src="https://github.com/tauri-apps/plugins-workspace/assets/133960549/cb2da246-895f-4b9c-9116-935db7170524">

**Comment by pymete** [comment]
if I run this command I get the same error window.

`msiexec src-tauri\target\release\bundle\msi\***_x64_en-US.msi /passive`

If I use the `/i` paramter before the msi file path the problem is solved.

`msiexec /i src-tauri\target\release\bundle\msi\***_x64_en-US.msi /passive`

**Comment by Runkang10** [comment]
Yeah, if everyone need parse this command to update is not really good.

**Comment by pymete** [comment]
> Wait in the updater plugin configuration, is the `windows` configuration still there or not?
> 
> In the repository documentation there are only `endpoints` and `pubkey`.
> 
> I found something here: https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/updater/tests/app-updater/tauri.conf.json
> 
> ![image](https://private-user-images.githubusercontent.com/164545653/338536455-6f1119f5-e706-44bf-92e0-07ed536d1214.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDA0OTYsIm5iZiI6MTcxODEwMDE5NiwicGF0aCI6Ii8xNjQ1NDU2NTMvMzM4NTM2NDU1LTZmMTExOWY1LWU3MDYtNDRiZi05MmUwLTA3ZWQ1MzZkMTIxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxMDAzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzM0M2JlMTMwN2VjNTIwYTIzYzVhMTU1ODIwYjU5YjEzODE3ZWRmYWI4ZjBlODk0NWI0MjMwMDMwY2JjM2FmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f9qaaofoeaDjP5AaEO7Klxn0qT7X4jemFdz6T4oHlco)

I didn't write this part (`plugins->updater->windows`) in the configuration because the default value is `/quiet`. Should I write it?

**Comment by Runkang10** [comment]
> > Wait in the updater plugin configuration, is the `windows` configuration still there or not?
> > In the repository documentation there are only `endpoints` and `pubkey`.
> > I found something here: https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/updater/tests/app-updater/tauri.conf.json
> > ![image](https://private-user-images.githubusercontent.com/164545653/338536455-6f1119f5-e706-44bf-92e0-07ed536d1214.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDA0OTYsIm5iZiI6MTcxODEwMDE5NiwicGF0aCI6Ii8xNjQ1NDU2NTMvMzM4NTM2NDU1LTZmMTExOWY1LWU3MDYtNDRiZi05MmUwLTA3ZWQ1MzZkMTIxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxMDAzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzM0M2JlMTMwN2VjNTIwYTIzYzVhMTU1ODIwYjU5YjEzODE3ZWRmYWI4ZjBlODk0NWI0MjMwMDMwY2JjM2FmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f9qaaofoeaDjP5AaEO7Klxn0qT7X4jemFdz6T4oHlco)
> 
> I didn't write this part (`plugins->updater->windows`) in the configuration because the default value is `/quiet`. Should I write it?

I don't know if this works but in the documentation doesn't say anything about `windows` argument.

**Comment by FabianLars** [comment]
Thanks for all the reports :) This is a consequence from https://github.com/tauri-apps/plugins-workspace/pull/1054, i assume only the nsis updater was tested in that PR because conceptually it can't work with msi installers. The PR changed the updater to call the updater bundles directly instead of going through powershell but .msi files are not executable by themselves so we must use `msiexec` again to install the `msi`.

**Comment by Runkang10** [comment]
So before I fix this, should I only use NSIS for my Tauri application to use the updater functionality (.exe Current to .exe New)?

**Comment by FabianLars** [comment]
Well, _right now_ where the msi installer is broken, yes. In general, you should decide on one installer type before distributing your app to your users because the updater needs to be the same format as the one used to install the app. (You can update from msi to nsis if nsis is in perMachine mode but you can't go back)

**Comment by Runkang10** [comment]
I have a question:
![image](https://github.com/tauri-apps/plugins-workspace/assets/164545653/30817613-c1bb-463e-b93b-5099844dcfb8)
How to change in .exe installer instead of Windows Installer (.msi) in Github Action workflow with Tauri Action?

**Comment by FabianLars** [comment]
Assuming the exe installer is already being uploaded you can add `updaterJsonPreferNsis: true` to the tauri-action step to make the action prefer the exe installer in latest.json.

**Comment by Runkang10** [comment]
> Assuming the exe installer is already being uploaded you can add `updaterJsonPreferNsis: true` to the tauri-action step to make the action prefer the exe installer in latest.json.

This is my workflow:
```
name: "Publish"

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__
          releaseName: "TextPad32 (TP32) v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
```

Where can i add `updaterJsonPreferNsis: true`?

**Comment by FabianLars** [comment]
```yml
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__
          releaseName: "TextPad32 (TP32) v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
          updaterJsonPreferNsis: true # <---
```
