### ISSUE TITLE
[log] Window stuck after click window close button

### ISSUE THREAD

**Issue by zengxs** [tauri-apps/plugins-workspace#170]
When clicking the window close button, the window gets stuck and the mouse pointer becomes like this:
![](https://help.apple.com/assets/61D4C1B5425F2576373C512A/61D4C1B7425F2576373C5132/zh_CN/157590d8922e581a6e14f6f9cdaba5b8.png)

And the log prints this:
```
[2022-05-09][16:05:52][tao::platform_impl::platform::window][TRACE] Dropping `UnownedWindow` (0x600001af5eb0)
[2022-05-09][16:05:52][tao::platform_impl::platform::window][TRACE] Dropping `UnownedWindow` (0x600001af5eb0)
```

This problem does not occur when `tauri-plugin-log` is removed.

System: Apple M1 + macOS 12.3.1
tauri-plugin-log revision: `d1fba58` (`release` branch)
Tauri version: `1.0.0-rc.6` to `1.0.0-rc.9` all have this problem

<details><summary>src-tauri/src/main.rs</summary>

```rust
#![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)]

use tauri_plugin_log::{LogTarget, LoggerBuilder};
use tauri_plugin_store::PluginBuilder;

fn main() {
    tauri::Builder::default()
        // .plugin(PluginBuilder::default().build())
        .plugin(
            LoggerBuilder::new()
                .target(LogTarget::LogDir)
                .target(LogTarget::Stdout)
                .target(LogTarget::Webview)
                .build(),
        )
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```
</details>

<details><summary>Cargo.toml</summary>

```toml
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-rc.8", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-rc.9", features = ["api-all"] }
tauri-plugin-store = { git = "https://github.com/tauri-apps/tauri-plugin-store.git", rev = "29585d5" }
tauri-plugin-log = { git = "https://github.com/tauri-apps/tauri-plugin-log.git", rev = "d1fba58", features = ["colored"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
```
</details>

<details><summary>Screenshot on stuck</summary>

<img width="912" alt="image" src="https://user-images.githubusercontent.com/18748098/167367044-9125a40e-8170-409c-90af-3812d3ed7150.png">

</details>

<details><summary>Full log</summary>

```
[2022-05-09][16:01:14][tao::platform_impl::platform::window][TRACE] Creating new window
[2022-05-09][16:01:14][tao::platform_impl::platform::window][TRACE] Creating new window
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Triggered `viewDidMoveToWindow`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Triggered `viewDidMoveToWindow`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Completed `viewDidMoveToWindow`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Completed `viewDidMoveToWindow`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::window][TRACE] Locked shared state in `set_fullscreen`
[2022-05-09][16:01:14][tao::platform_impl::platform::window][TRACE] Locked shared state in `set_fullscreen`
[2022-05-09][16:01:14][tao::platform_impl::platform::window][TRACE] Unlocked shared state in `set_fullscreen`
[2022-05-09][16:01:14][tao::platform_impl::platform::window][TRACE] Unlocked shared state in `set_fullscreen`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Triggered `viewDidMoveToWindow`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Triggered `viewDidMoveToWindow`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Completed `viewDidMoveToWindow`
[2022-05-09][16:01:14][tao::platform_impl::platform::view][TRACE] Completed `viewDidMoveToWindow`
[2022-05-09][16:01:14][tao::platform_impl::platform::app_delegate][TRACE] Triggered `applicationDidFinishLaunching`
[2022-05-09][16:01:14][tao::platform_impl::platform::app_delegate][TRACE] Triggered `applicationDidFinishLaunching`
[2022-05-09][16:01:14][tao::platform_impl::platform::app_state][TRACE] Activating visible window
[2022-05-09][16:01:14][tao::platform_impl::platform::app_state][TRACE] Activating visible window
[2022-05-09][16:01:14][tao::platform_impl::platform::app_delegate][TRACE] Completed `applicationDidFinishLaunching`
[2022-05-09][16:01:14][tao::platform_impl::platform::app_delegate][TRACE] Completed `applicationDidFinishLaunching`
[2022-05-09][16:01:14][tao::platform_impl::platform::window_delegate][TRACE] Triggered `windowDidBecomeKey:`
[2022-05-09][16:01:14][tao::platform_impl::platform::window_delegate][TRACE] Triggered `windowDidBecomeKey:`
[2022-05-09][16:01:14][tao::platform_impl::platform::window_delegate][TRACE] Completed `windowDidBecomeKey:`
[2022-05-09][16:01:14][tao::platform_impl::platform::window_delegate][TRACE] Completed `windowDidBecomeKey:`
[2022-05-09][16:01:16][tao::platform_impl::platform::window_delegate][TRACE] Triggered `windowShouldClose:`
[2022-05-09][16:01:16][tao::platform_impl::platform::window_delegate][TRACE] Triggered `windowShouldClose:`
[2022-05-09][16:01:16][tao::platform_impl::platform::window_delegate][TRACE] Completed `windowShouldClose:`
[2022-05-09][16:01:16][tao::platform_impl::platform::window_delegate][TRACE] Completed `windowShouldClose:`
[2022-05-09][16:01:16][tao::platform_impl::platform::window][TRACE] Dropping `UnownedWindow` (0x6000002ec7e0)
[2022-05-09][16:01:16][tao::platform_impl::platform::window][TRACE] Dropping `UnownedWindow` (0x6000002ec7e0)
```
</details>
