### ISSUE TITLE
[sql] What version should I install?

### ISSUE THREAD

**Issue by RSurya99** [tauri-apps/plugins-workspace#202]
Hello, I want to try this plugin, I have installed the same version as in your readme file, but it ended up getting an error `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'notify')`.

Can someone tell me what commit should I use to install this package?

Project detail :
- "vue": "^2.6.14"
- "vue-cli-plugin-tauri": "~1.0.0-rc.1"
- "tauri-plugin-sql-api": "github:tauri-apps/tauri-plugin-sql#2be17fae3832e55a18c0beaf7b76f341e7a755da",

**Comment by RSurya99** [comment]
And also where I can put my sqlite file?

The readme is only say that the path is relative to `tauri::api::path::BaseDirectory::App`.

But I don't know where is `tauri::api::path::BaseDirectory::App` or how to set up it

**Comment by lukethacoder** [comment]
Currently using without any issues.

**package.json**
```json
"tauri-plugin-sql-api": "github:tauri-apps/tauri-plugin-sql#b13efd1e9d8f6c862b67917f3c62536ed1c64e9c",
```

**Cargo.toml**
```toml
[dependencies]
tauri-plugin-sql = { git = "https://github.com/tauri-apps/tauri-plugin-sql", rev = "b13efd1e9d8f6c862b67917f3c62536ed1c64e9c", features = ["sqlite"] }
```

Recently updated my packages and noticed things weren't playing so nicely so sticking with this rev for now.
