### ISSUE TITLE
[sql] How to install

### ISSUE THREAD

**Issue by barbalex** [tauri-apps/plugins-workspace#211]
I tried to install tauri-plugin-sql but am running into some problems. Not sure what I misunderstood, what may not be well enough documented and where I simply made mistakes. I am a complete tauri / rust noob.

# 1 Installation
I did the following:

### 1.1 tauri
Installed tauri into my existing app according to the [instructions](https://tauri.studio/en/docs/usage/development/integration/#2-initialize-tauri-in-your-app).

### 1.2 tauri-plugin-sql
Installed tauri-plugin-sql 
```
yarn add github:tauri-apps/tauri-plugin-sql#488558717b77d8a2bcb37acfd2eca9658aeadc8e
```
as shown [in the readme](https://github.com/tauri-apps/tauri-plugin-sql#webview). 

While doing this I ran into a discrepancy: the package.json entry is
```json
"tauri-plugin-sql": "github:tauri-apps/tauri-plugin-sql#488558717b77d8a2bcb37acfd2eca9658aeadc8e"
```
instead of 
```json
"tauri-plugin-sql-api": "github:tauri-apps/tauri-plugin-sql#v0.1.0"
```

My package.json now looks like this:
```json
{
  "name": "kapla5",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@tauri-apps/api": "^1.0.0-beta.8",
    "bootstrap": "4.5.3",
    "date-fns": "2.23.0",
    "exceljs": "4.3.0",
    "jquery": "3.6.0",
    "lodash": "4.17.21",
    "mobx": "6.3.3",
    "mobx-react": "7.2.0",
    "mobx-react-lite": "3.2.1",
    "mobx-state-tree": "5.0.2",
    "moment": "2.29.1",
    "prop-types": "15.7.2",
    "react": "17.0.2",
    "react-datepicker": "4.2.1",
    "react-dom": "17.0.2",
    "react-dropzone": "11.3.4",
    "react-error-boundary": "3.1.3",
    "react-icons": "4.2.0",
    "react-linkify": "0.x",
    "react-scripts": "4.0.3",
    "react-select": "4.3.1",
    "react-split-pane": "0.1.92",
    "react-textarea-autosize": "8.3.3",
    "react-virtualized": "9.22.3",
    "reactstrap": "8.10.0",
    "styled-components": "5.3.1",
    "tauri-plugin-sql": "github:tauri-apps/tauri-plugin-sql#488558717b77d8a2bcb37acfd2eca9658aeadc8e",
    "use-debounce": "7.0.0",
    "use-detect-print": "0.0.2",
    "username": "6.0.0",
    "web-vitals": "1.0.1"
  },
  "devDependencies": {
    "@tauri-apps/cli": "^1.0.0-beta.10",
    "@testing-library/jest-dom": "5.11.4",
    "@testing-library/react": "11.1.0",
    "@testing-library/user-event": "12.1.10",
    "prettier": "2.4.0"
  },
  "peerDependencies": {
    "popper.js": "1.16.1",
    "react-is": "17.0.2"
  },
  "scripts": {
    "dev": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "tauri": "tauri"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  }
}
```

### 1.3 edit ´src-tauri/Cargo.toml´
The readme shows:
```toml
[dependencies.tauri-plugin-sql]
git = "https://github.com/tauri-apps/tauri-plugin-sql"
tag = "v0.1.0"
features = ["sqlite"] # or "postgres", or "mysql"
#branch = "main"
```

I tried to get it working using:
```toml
[dependencies.tauri-plugin-sql]
git = "https://github.com/tauri-apps/tauri-plugin-sql"
commit = "488558717b77d8a2bcb37acfd2eca9658aeadc8e"
features = ["sqlite"]
branch = "release"
```
as v0.1.0 does not seem to exist.

My ´src-tauri/Cargo.toml´ now looks like this:
```toml
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-beta.8", features = ["api-all"] }

[dependencies.tauri-plugin-sql]
git = "https://github.com/tauri-apps/tauri-plugin-sql"
commit = "488558717b77d8a2bcb37acfd2eca9658aeadc8e"
features = ["sqlite"]
branch = "release"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
```

I tried to write this like it is done for tauri itself. But got messages saying, commit had been ommited. Which seems to still be a problem, see the result further down. It could very well be that:
- I got the way to refer to a commit wrong
- I am referring to the wrong commit?

### 1.4 edit ´src-tauri/src/main.rs´
The readme says:
```rs
use tauri_plugin_sql::TauriSql;

fn main() {
    tauri::Builder::default()
        .plugin(TauriSql::default())
        .build()
        .run();
}
```

My file now looks like this:
```rs
#![cfg_attr(
  all(not(debug_assertions), target_os = "windows"),
  windows_subsystem = "windows"
)]

use tauri_plugin_sql::TauriSql;

fn main() {
  tauri::Builder::default()
  .plugin(TauriSql::default())
    .run(tauri::generate_context!())
     .expect("error while running tauri application");
}
```
I had to change from the readme example as that did not work. Being a complete rust noob it could very well be that there is a mistake here.

# 2 Result
When I run `yarn tauri dev` I get:
```
PS C:\Users\alexa\kapla5> yarn tauri dev
yarn run v1.22.17
$ tauri dev
 app:spawn Running "C:\Users\alexa\kapla5\node_modules\@tauri-apps\cli\bin\tauri-cli.exe tauri dev" +0ms

warning: unused manifest key: dependencies.tauri-plugin-sql.commit
   Compiling app v0.1.0 (C:\Users\alexa\kapla5\src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 3.28s
     Running `target\debug\app.exe`
```

The problem is: A tauri window opens but it can't access the site.
In the console this error appears:
```
crbug/1173575, non-JS module files deprecated.
```

I tried to dumb down my code to the absolute minimum. As I am converting an electron app I replaced the entire app part by rendering `<div>hello world</div>` without importing tauri-plugin-sql anywhere yet.
