### ISSUE TITLE
[store] store.save() does not work

### ISSUE THREAD

**Issue by a-khanna** [tauri-apps/plugins-workspace#225]
Cargo toml:
```toml
[build-dependencies]
tauri-build = { version = "1.0.0-rc.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-rc.4", features = ["clipboard-all", "dialog-all", "fs-read-file", "fs-write-file", "shell-all", "window-all"] }

[dependencies.tauri-plugin-store]
git = "https://github.com/tauri-apps/tauri-plugin-store"
branch = "dev"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
```
main.rs:
```rust
#![cfg_attr(
  all(not(debug_assertions), target_os = "windows"),
  windows_subsystem = "windows"
)]

use tauri_plugin_store::PluginBuilder;

fn main() {
  tauri::Builder::default()
    .plugin(PluginBuilder::default().build())
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
```
package.json:
```json
{
  "dependencies": {
    "tauri-plugin-store-api": "github:tauri-apps/tauri-plugin-store#dev",
  }
}
```
React code:
```js
const store = new Store('.settings.dat');

let storeBases = await store.get('bases') as number[];
storeBases = storeBases ? [...storeBases, baseToAdd] : [baseToAdd];
await store.set('bases', storeBases);
await store.save();
```
The store operations work till the app is running (navigating away or into this page).
But the settings file is not persisted on disk and subsequent runs have a blank store.
I also have both `readFile` and `writeFile` enabled in the `allowList`.
