### ISSUE TITLE
[window-state] When will there be a new release ?

### ISSUE THREAD

**Issue by ClementGre** [tauri-apps/plugins-workspace#242]
Hi,
it's been more than a year since the last release, and a lot of issues have been solved during this time.

It would be amazing to have a new release. The code changed a lot and I would love to have the new code (which would solve issues I have), without having to copy/paste the code in my project.

**Comment by FabianLars** [comment]
We're currently reworking our plugin infrastructure, see [tauri-apps/plugins-workspace](https://github.com/tauri-apps/plugins-workspace/). Once that's done, we'll polish the plugins and release them.

Btw you can use this plugin from git just fine (which you have to do for all other plugins because they were not released at all)

For example to alwazs pull the latest dev branch:
```toml
[dependencies]
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/tauri-plugin-window-state" }
```
You can also lock it to a commit by adding `rev = "commit hash"``
