### ISSUE TITLE
[window-state] error: could not compile `tauri-runtime-wry` due to 2 previous errors

### ISSUE THREAD

**Issue by elibroftw** [tauri-apps/plugins-workspace#250]
I added `tauri-plugin-window-state` to Cargo.toml as seen below
```toml
[build-dependencies]
tauri-build = { version = "1.0.0-rc.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
# fails to build even if I use the below
# tauri = { git = "https://github.com/tauri-apps/tauri", branch = "next", features = ["api-all"] }
tauri = { version = "1.0.0-rc.4", features = ["api-all"] }
toml = "0.5"
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/tauri-plugin-window-state", tag = "tauri-plugin-window-
state-v0.1.0" }
```

When I added this, `wry` could not be compiled for some reason???

```rs
   Compiling tauri-runtime-wry v0.2.1 (https://github.com/tauri-apps/tauri/?branch=next#43348652)
error[E0277]: the trait bound `ICoreWebView2FocusChangedEventHandler: IntoParam<'_, webview2_com_sys::Microsoft::Web::WebView2::Win32::ICoreWebView2FocusChangedEventHandler>` is not satisfied
    --> C:\Users\maste\.cargo\git\checkouts\tauri-9dcc2f9152472c1a\4334865\core\tauri-runtime-wry\src\lib.rs:1715:15
     |
1714 |               controller.GotFocus(
     |                          -------- required by a bound introduced by this call
1715 | /               FocusChangedEventHandler::create(Box::new(move |_, _| {
1716 | |                 let _ = proxy.send_event(Message::Webview(
1717 | |                   id,
1718 | |                   WebviewMessage::WebviewEvent(WebviewEvent::Focused(true)),
1719 | |                 ));
1720 | |                 Ok(())
1721 | |               })),
     | |_________________^ the trait `IntoParam<'_, webview2_com_sys::Microsoft::Web::WebView2::Win32::ICoreWebView2FocusChangedEventHandler>` is not implemented for `ICoreWebView2FocusChangedEventHandler`
     |
     = help: the following implementations were found:
               <&ICoreWebView2FocusChangedEventHandler as IntoParam<'a, IUnknown>>
               <ICoreWebView2FocusChangedEventHandler as IntoParam<'a, IUnknown>>

error[E0277]: the trait bound `ICoreWebView2FocusChangedEventHandler: IntoParam<'_, webview2_com_sys::Microsoft::Web::WebView2::Win32::ICoreWebView2FocusChangedEventHandler>` is not satisfied
    --> C:\Users\maste\.cargo\git\checkouts\tauri-9dcc2f9152472c1a\4334865\core\tauri-runtime-wry\src\lib.rs:1729:15
     |
1728 |               controller.LostFocus(
     |                          --------- required by a bound introduced by this call
1729 | /               FocusChangedEventHandler::create(Box::new(move |_, _| {
1730 | |                 let _ = proxy.send_event(Message::Webview(
1731 | |                   id,
1732 | |                   WebviewMessage::WebviewEvent(WebviewEvent::Focused(false)),
1733 | |                 ));
1734 | |                 Ok(())
1735 | |               })),
     | |_________________^ the trait `IntoParam<'_, webview2_com_sys::Microsoft::Web::WebView2::Win32::ICoreWebView2FocusChangedEventHandler>` is not implemented for `ICoreWebView2FocusChangedEventHandler`
     |
     = help: the following implementations were found:
               <&ICoreWebView2FocusChangedEventHandler as IntoParam<'a, IUnknown>>
               <ICoreWebView2FocusChangedEventHandler as IntoParam<'a, IUnknown>>

For more information about this error, try `rustc --explain E0277`.
error: could not compile `tauri-runtime-wry` due to 2 previous errors
```
