### ISSUE TITLE
[window-state] Does not work with custom titlebar (appWindow.close)

### ISSUE THREAD

**Issue by AllanChain** [tauri-apps/plugins-workspace#254]
When I close the app with [`appWindow.close`](https://tauri.studio/en/docs/usage/guides/visual/window-customization/#js) and reopen the app, the window position is not preserved.

It seems that closing app with `appWindow.close` does not trigger a `CloseRequested` event, so the state is not read.

If I close the window with system titlebar and reopen the app, the window position is preserved. So I can confirm it's about `appWindow.close`.

**Comment by nothingismagick** [comment]
this is great to know, however we need to know about the results of `tauri info` please.

**Comment by AllanChain** [comment]
<details>
<summary><b>Edited</b> I was using pnpm as package manager, <code>tauri info</code> does not work. Expand to see details.</summary>


```
 app:spawn Running "D:\Desktop\Program\Repo\taulock\node_modules\.pnpm\@tauri-apps+cli@1.0.0-beta.10\node_modules\@tauri-apps\cli\bin\tauri-cli.exe tauri info" +0ms


Operating System - Windows, version 10.0.22000 X64
Webview2 - 94.0.992.31

Node.js environment
  Node.js - 14.16.1
  @tauri-apps/cli - 1.0.0-beta.10
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', src\info.rs:323:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  @tauri-apps/api - tauri-apps
 app:spawn Command "D:\Desktop\Program\Repo\taulock\node_modules\.pnpm\@tauri-apps+cli@1.0.0-beta.10\node_modules\@tauri-apps\cli\bin\tauri-cli.exe" failed with exit code: 101 +1ms
```

And part of `package.json`:
```
"@tauri-apps/cli": "^1.0.0-beta.10",
"@tauri-apps/api": "^1.0.0-beta.8",
```

`Cargo.toml`:

```toml
[build-dependencies]
tauri-build = { version = "1.0.0-beta.3" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
# tauri = { version = "1.0.0-beta.8", features = ["window-all"] }
[dependencies.tauri]
git = "https://github.com/tauri-apps/tauri/"
branch = "next"
features = ["window-all"]
[dependencies.tauri-plugin-window-state]
git = "https://github.com/tauri-apps/tauri-plugin-window-state"
branch = "dev"
```
</details>

---

And here is the output after switching to npm:

```
Downloading Rust CLI...
Download Complete
 app:spawn Running "D:\Desktop\Program\Repo\taulock\node_modules\@tauri-apps\cli\bin\tauri-cli.exe tauri info" +0ms


Operating System - Windows, version 10.0.22000 X64
Webview2 - 94.0.992.31

Node.js environment
  Node.js - 14.16.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.23.0
  yarn - 1.22.10

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/.git
/dist
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - target/webpack_dist
  devPath - target/webpack_dist
  framework - Vue.js (Vue CLI)
  bundler - Webpack
```
