### ISSUE TITLE
[bug] After upgrading to 2.5.0, use http plug-in to request the interface, but no response is received.

### ISSUE THREAD

**Issue by nongyehong** [tauri-apps/plugins-workspace#2638]
### Describe the bug

After upgrading to 2.5.0, use http plug-in to request the interface, but no response is received.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.5.0 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.86.0 (05f9846f8 2025-03-31)
    ✔ cargo: 1.86.0 (adf9b6ad1 2025-02-28)
    ✔ rustup: 1.28.1 (f9edccde0 2025-03-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 22.11.0
    - pnpm: 9.15.0
    - yarn: 1.22.22
    - npm: 10.9.0
    - bun: 1.1.36

[-] Packages
    - tauri 🦀: 2.5.0
    - tauri-build 🦀: 2.2.0
    - wry 🦀: 0.51.2
    - tao 🦀: 0.33.0
    - @tauri-apps/api : 2.5.0
    - @tauri-apps/cli : 2.5.0

[-] Plugins
    - tauri-plugin-shell 🦀: 2.2.1
    - @tauri-apps/plugin-shell : 2.2.1
    - tauri-plugin-notification 🦀: 2.2.2
    - @tauri-apps/plugin-notification : 2.2.2
    - tauri-plugin-http 🦀: 2.4.3
    - @tauri-apps/plugin-http : 2.4.3
    - tauri-plugin-updater 🦀: 2.6.1, (outdated, latest: 2.7.0)
    - @tauri-apps/plugin-updater : 2.6.1 (outdated, latest: 2.7.0)
    - tauri-plugin-sql 🦀: 2.2.0
    - @tauri-apps/plugin-sql : 2.2.0
    - tauri-plugin-os 🦀: 2.2.1
    - @tauri-apps/plugin-os : 2.2.0 (outdated, latest: 2.2.1)
    - tauri-plugin-process 🦀: 2.2.0, (outdated, latest: 2.2.1)
    - @tauri-apps/plugin-process : 2.2.0 (outdated, latest: 2.2.1)
    - tauri-plugin-fs 🦀: 2.2.1
    - @tauri-apps/plugin-fs : 2.2.0 (outdated, latest: 2.2.1)
    - tauri-plugin-clipboard-manager 🦀: 2.2.2
    - @tauri-apps/plugin-clipboard-manager : 2.2.2
    - tauri-plugin-single-instance 🦀: 2.2.2, (outdated, latest: 2.2.3)
    - @tauri-apps/plugin-single-instance : not installed!
    - tauri-plugin-autostart 🦀: 2.2.0, (outdated, latest: 2.3.0)
    - @tauri-apps/plugin-autostart : 2.2.0 (outdated, latest: 2.3.0)
    - tauri-plugin-upload 🦀: 2.2.1
    - @tauri-apps/plugin-upload : not installed!
    - tauri-plugin-dialog 🦀: 2.2.0, (outdated, latest: 2.2.1)
    - @tauri-apps/plugin-dialog : 2.2.0 (outdated, latest: 2.2.1)
    - tauri-plugin-global-shortcut 🦀: 2.2.0
    - @tauri-apps/plugin-global-shortcut : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://127.0.0.1:6130/
    - framework: Vue.js
    - bundler: Rollup
```

### Stack trace

```text

```

**Comment by FabianLars** [comment]
does it return any errors? do you have some code for us to try maybe?

**Comment by jlvihv** [comment]
I have the same issue, you just need to send any fetch request and then try to read the content to reproduce, for example:

import { fetch } from '@tauri-apps/plugin-http';
const resp = await fetch(someUrl)
const html = await resp.text();  It can get stuck here

**Comment by nongyehong** [comment]
> does it return any errors? do you have some code for us to try maybe?

No error is reported, no response content is obtained after the request.

**Comment by jlvihv** [comment]
My solution now is to downgrade to 2.4.1. I think the problem is in this commit: https://github.com/tauri-apps/plugins-workspace/commit/a15eedf37854344f7ffbcb0d373d848563817011

**Comment by FabianLars** [comment]
@amrbashir since you're the most familiar one of us with the plugin atm, do you have time to take a look?

**Comment by brtinney** [comment]
> My solution now is to downgrade to 2.4.1. I think the problem is in this commit: [a15eedf](https://github.com/tauri-apps/plugins-workspace/commit/a15eedf37854344f7ffbcb0d373d848563817011)

I had to go down to 2.3.0. I am not trying to stream anything, so I don't need that functionality, and it seems like when that was added, things broke for just parsing a JSON body somehow.

For context, I am using unjs/ofetch, but it was just never returning [after `.text()` was called](https://github.com/unjs/ofetch/blob/c817be86e8758ed7e6a05d2589f4b318f1f0b38e/src/fetch.ts#L223). I used the debugger to determine it got to the [`invoke`](https://github.com/tauri-apps/plugins-workspace/blob/c5b0f51cfd911cca9317b59efc718b570980129b/plugins/http/guest-js/index.ts#L256) and never returned.

**Comment by amrbashir** [comment]
seems similar to https://github.com/tauri-apps/plugins-workspace/issues/2564, can you all try https://github.com/tauri-apps/plugins-workspace/pull/2562 (make sure to build the JS api locally)

**Comment by daveycodez** [comment]
I just did cargo upgrade and it fixed this for me o_O

**Comment by nongyehong** [comment]
> I just did cargo upgrade and it fixed this for me o_O

What version of tauri are you using? 🧐

**Comment by daveycodez** [comment]
> > I just did cargo upgrade and it fixed this for me o_O
> 
> What version of tauri are you using? 🧐

```json
{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "default",
  "description": "enables the default permissions",
  "windows": [
    "main"
  ],
  "permissions": [
    "core:default",
    {
      "identifier": "http:default",
      "allow": [
        { "url": "https://*:*" },
        { "url": "http://*:*" }
      ]
    },
    "deep-link:default",
    "opener:default"
  ]
}
```


```toml
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.5.1", features = [] }
tauri-plugin-log = "2.4.0"
tauri-plugin-http = { version = "2", features = ["cookies", "unsafe-headers"] } 
tauri-plugin-deep-link = "2"
tauri-plugin-opener = "2"
objc2-app-kit = "0.3.1"
objc2-web-kit = "0.3.1"
```
