### ISSUE TITLE
[localhost] [bug] Running gives AssetNotFound("index.html")

### ISSUE THREAD

**Issue by ManeraKai** [tauri-apps/plugins-workspace#388]
Tested on a fresh Vanilla JS initialization.

Here's my Cargo.toml, I just added the plugin and portpicker:
```toml
[package]
name = "testing"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.3", features = [] }

[dependencies]
tauri = { version = "1.3", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri-plugin-localhost = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
portpicker = "0.1" # used in the example to pick a random free port

[features]
custom-protocol = ["tauri/custom-protocol"]
```

And here is my main.rs
```rust
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use tauri::{utils::config::AppUrl, window::WindowBuilder, WindowUrl};

fn main() {
  let port = portpicker::pick_unused_port().expect("failed to find unused port");

  let mut context = tauri::generate_context!();
  let url = format!("http://localhost:{}", port).parse().unwrap();
  let window_url = WindowUrl::External(url);
  // rewrite the config so the IPC is enabled on this URL
  context.config_mut().build.dist_dir = AppUrl::Url(window_url.clone());
  context.config_mut().build.dev_path = AppUrl::Url(window_url.clone());

  tauri::Builder::default()
    .plugin(tauri_plugin_localhost::Builder::new(port).build())
    .setup(move |app| {
      WindowBuilder::new(app, "main".to_string(), window_url)
        .title("Localhost Example")
        .build()?;
      Ok(())
    })
    .run(context)
    .expect("error while running tauri application");
}
```

And it gives this:
![image](https://github.com/tauri-apps/plugins-workspace/assets/40805353/48033f5e-e41f-4daa-bb2a-d630fbb146d5)
