### ISSUE TITLE
[sql] sql plugin cannot compile on Windows aarch64  

### ISSUE THREAD

**Issue by Pylogmon** [tauri-apps/plugins-workspace#659]
I found that `sql` plugin could not compile on Windows arch64. After investigation, I found that it was caused by the `rustls` dependency introduced by `sqlx` and the `ring` dependency introduced by `rustls` not supporting Windows arch 64. Is this feature of sqlx necessary, I don't have much knowledge about this topic. I would greatly appreciate it if you could help me clear up my confusion.

**Comment by FabianLars** [comment]
It should _not_ be required if you only want the sqlite backend. If you also need postgres or mysql then it's required and you'll have to wait until rustls & sqlx update to the new ring version (0.17 supports aarch64 on windows now).

So to get sqlite working on aarch64 we only have to move around the rustls sqlx feature flag from the dependency to the respective feature flags here https://github.com/tauri-apps/plugins-workspace/blob/v1/plugins/sql/Cargo.toml :)

**Comment by Pylogmon** [comment]
Thank you very much for your reply!

In that case, in my humble opinion, isn't it better to write like this?

```toml
[features]
sqlite = ["sqlx/sqlite", "sqlx/runtime-tokio"]
mysql = ["sqlx/mysql", "sqlx/runtime-tokio-rustls"]
postgres = ["sqlx/postgres", "sqlx/runtime-tokio-rustls"]
```
