### ISSUE TITLE
[window-state] not working near to screen borders

### ISSUE THREAD

**Issue by romby1** [tauri-apps/plugins-workspace#892]
If I place window to the borders of the screen it's not restoring at the same place, but on the previous position before that. In others cases it's restoring correctly 

https://github.com/tauri-apps/plugins-workspace/assets/68077065/9befa3a2-0df8-4373-ba3b-c923d65389de

link to the plugin https://github.com/tauri-apps/tauri-plugin-window-state

**Comment by amrbashir** [comment]
can you test if #898 fixes the issue for you?

add the following in your `Cargo.toml` then run `cargo update` inside `src-tauri`:
```toml
[patch.crates-io]
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "fix/window-state/restore-zero-positions" } 
```
